env:
  DOCKER_COMPOSE_VERSION: 1.8.0
  global:
    - CC_TEST_REPORTER_ID=09e48e4c16a44745de87a5aa5471dcfa53db8b868d9419e2e5d7a3312599e641

language: ruby
rvm:
  - 2.6.3

before_install:
  - docker-compose build

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r 09e48e4c16a44745de87a5aa5471dcfa53db8b868d9419e2e5d7a3312599e641