sudo: false

language: ruby

rvm:
  - 2.6.3

services:
  - docker

before_install:
  - docker build -t ilm .
  - docker run -v ~/ilm:/ilm:ro git-bash
  - docker ps -a
  - gem install bundler

script:
  - bundle exec rake test
